image:
  file: .docker/gitpod.Dockerfile
  context: .
tasks:
  - name: Pages Server
    command: sudo /init
    openMode: split-right
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8443
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 9000
    onOpen: ignore
