image:
  file: .docker/gitpod.Dockerfile
  context: .

checkoutLocation: "/var/www"
workspaceLocation: "."

tasks:
  - init: |
      gp env S6_KEEP_ENV=1
      gp env APP_ENV=development
    command: sudo /init
    name: Pages Server
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8443
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 9000
    onOpen: ignore
