image:
  file: Dockerfile
  context: .
tasks:
  - name: S6 init
    command: /bin/execlineb /init
    openMode: split-right
ports:
  - port: 8080
  - port: 8443
  - port: 8081
    onOpen: open-preview
  - port: 8082
    onOpen: open-preview