image:
  file: .docker/gitpod.Dockerfile
  context: .

tasks:
  - init: |
      sudo gp env S6_KEEP_ENV=1
      sudo gp env APP_ENV=development
    command: /init
    name: Pages Server
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8443
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 9000
    onOpen: ignore
