image:
  file: .docker/gitpod.Dockerfile
  context: .

tasks:
  - openMode: split-right
    command: sudo /init
    name: Pages Server

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8443
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 9000
    onOpen: ignore
