image:
  file: .gitpod/Dockerfile
  context: .

checkoutLocation: "joomlatools-server"

tasks:

  - name: Logs - Joomlatools Server
    init: |
      export APP_NAME=joomlatools-server
      export APP_ENV=development
      export APP_PRELOAD=off
      export APP_CACHE=off
      export APP_DEBUG=on
      export COMPOSER_NO_DEV=1
    command: |
      clear
      sudo -E /init

  - name: Composer - Joomlatools Server
    command: sudo /bin/bash -e /var/scripts/composer_install.sh

  - name: Install Latest Joomla
    command: sudo joomla site:create joomla --release=latest --www=/workspace/joomlatools-server/sites

  - name: Install Latest Wordpress
    command: sudo folioshell site:create joomla --release=latest --www=/workspace/joomlatools-server/sites

  - name: Terminal - Joomlatools Server
    command: |
      clear
      echo ""
      echo "Commands you can try:"
      echo " * gp preview $(gp url 8080)/__info/php-info"
      echo " * mason"

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 8443
    onOpen: ignore
  - port: 9000
    onOpen: ignore
    visibility: private
  - port: 3306
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - cweijan.vscode-mysql-client2
    - bmewburn.vscode-intelephense-client
    - ecmel.vscode-html-css
