image:
  file: .gitpod/Dockerfile
  context: .

checkoutLocation: "joomlatools-server"

tasks:

   - name: Shell - Joomlatools Server
    command: |
      clear
      echo ""
      echo "Commands you can try:"
      echo " * gp preview $(gp url 80)/joomla/"
      echo " * gp preview $(gp url 80)/joomla/administrator/"
      echo " * gp preview $(gp url 80)/__info/php-info"
      echo " * joomla"
      echo " * mason"

   - name: Logs - Joomlatools Server
   command: |
     clear
     sudo -E /init

ports:
  - port: 80
    onOpen: open-preview
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 8083
    onOpen: ignore
  - port: 9000
    onOpen: ignore
    visibility: private
  - port: 3306
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - cweijan.vscode-mysql-client2
    - bmewburn.vscode-intelephense-client
    - ecmel.vscode-html-css
