image:
  file: .docker/gitpod.Dockerfile
  context: .

checkoutLocation: "pages-server"

tasks:
  - init: |
      gp env APP_ENV=staging
    command: sudo -E /init
    name: Pages Server
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8443
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 9000
    onOpen: ignore
