#docker-compose.yml (Development)
version: "3.8"
services:
  joomlatools-server:
    image: joomlatools-server
    hostname: joomlatools-server
    container_name: joomlatools-server
    restart: always
    environment:
      - APP_NAME=joomlatools-server
      - APP_ENV=development
      - APP_DEBUG=on
      - APP_CACHE=off
      - APP_PRELOAD=off
    build:
      context: .
      args:
        IMAGE_TAG: latest
    env_file:
      - .env
    volumes:
      - ./sites/:/var/www/sites

      # Sites Cache
      - ./volume:/mnt/www/sites

      # MySQL Data
      - mysql:/mnt/www/mysql

      # Include any of the following for local development

      # Composer Vendor
      #- ./vendor:/tmp/www/vendor

      # Joomlatools Framework
      #- ~/Projects/joomlatools-framework:/var/www/[site]/joomla/libraries/joomlatools/code

      # Joomlatools Pages
      #- ~/Projects/joomlatools-pages:/var/www/sites/[site]/libraries/joomlatools-components/pages/code

    ports:
      #- "80:80"  # HTTP Apache
      #- "443:443"  # HTTPS Apache
      - "8080:8080"  # HTTP Apache
      - "8443:8443"  # HTTPS Apache
      - "3306:3306"    # MySQL
      - "33060:33060"  # MySQL - X Plugin

  #docker compose --profile phpmyadmin up
  phpmyadmin:
    profiles: ["phpmyadmin"]
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=joomlatools-server
      - PMA_VERBOSE=joomlatools-server
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=root
    ports:
      - "8180:80" # phpMyAdmin Server
    depends_on:
      - joomlatools-server

  #docker compose --profile mailhog up
  mailhog:
    profiles: ["mailhog"]
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # http server
    depends_on:
      - joomlatools-server

volumes:
  mysql: