globals:
  www: /var/www/sites
  mysql-login: "admin:admin"
  restart-command: s6-svc -r /var/run/s6/services/apache
  vhost: false
#"vhost:create":
#  folder: /var/www/sites/[site]/config/apache
#  filename: server.conf
#  template: /root/.foliolabs/folioshell/templates/apache-template.conf
#"vhost:remove":
#  folder: /var/www/sites/[site]/config/apache
#  filename: server.conf
